@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.demo.SignupController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_134842393 { 
   	label=demo
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   DBConn813456180[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DBConn</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ connectDB(): Connection</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SignupController813456180[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SignupController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   addressTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cityTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   confirmPassword: PasswordField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   emailIdTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   firstNameTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lastNameTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   passwordField: PasswordField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   phoneNumberTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   signUp: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stateChoice: ChoiceBox [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stateId: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   zipCodeTextField: TextField [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ BackToLogin(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addUser(emailId: String, userPassword: String, fName: String, lName: String, streetAdd: String, city: String, state: int, phoneNumber: String, zipCode: String, roleID: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ checkForEmail(emailId: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ infoBox(infoMessage: String, headerText: String, title: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ initialize(url: URL, resourceBundle: ResourceBundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ printSQLException(ex: SQLException)</TD></TR>
<TR><TD ALIGN="LEFT" >- showAlert(owner: Window, message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ signUp()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    

    
}
@enduml